version: '3.8'

services:

  devnote_db:
    image: postgres
    container_name: devnote_db
    restart: always
    env_file:
      - './docker/postgresql/.env'
    ports: 
      - '5432:5432'
    expose: 
      - '5432'
    command: 
      - '-c'
      - 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './docker/postgresql/my-postgresql.conf:/etc/postgresql/postgresql.conf'
      - 'devnote-data-db:/var/lib/postgresql/data'
    networks: 
      - 'devnote-network'

networks:
  devnote-network:
    driver: bridge

volumes:
  devnote-data-db: